version: '3.8'
services:
  metacore:
    container_name: metacore
    image: dcenttech/metacore:latest
    volumes:
      - ./config/webapp:/app/config/webapp
    environment:
      - "NODE_ENV=production"
      - "NODE_PORT=3021"
      - "DATABASE_HOST=172.22.0.3"
      - "DATABASE_PORT=5432"
      - "DATABASE_NAME=metacubic_dev"
      - "DATABASE_USER=systemadmin"
      - "DATABASE_PASSWORD=D3v!L1981!Killer00!"
      - "DATABASE_SCHEMA=meu"
      - "JWT_SECRET=metacubic"
      - "JWT_EXPIRATION_TIME=86400"
    ports:
      - "3021:3021"
    depends_on:
      - pgdb
    restart: always
    networks:
      - hypercube

  pgdb:
    container_name: metacubic_db
    image: postgres:latest
    volumes:
      - ./config/pgdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=systemadmin"
      - "POSTGRES_PASSWORD=D3v!L1981!Killer00!"
      - "POSTGRES_DB=metacubic"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - hypercube

  pgdbadmin:
    container_name: metacubic_dbadmin
    image: dpage/pgadmin4:latest
    environment:
      - "PGADMIN_DEFAULT_EMAIL=support@metacubic.org"
      - "PGADMIN_DEFAULT_PASSWORD=Killer00!D3v!L1981!"
    ports:
      - "5050:80"
    restart: always
    networks:
      - hypercube

networks:
  hypercube:
    driver: bridge
  host:
    external: true
    name: host

